export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      commitment: {
        Row: {
          action: string | null
          base_year: string | null
          commitment_deadline: string | null
          commitment_type: string | null
          company_name: string
          company_temperature_alignment: string | null
          date_published: string | null
          full_target_language: string | null
          lei: string | null
          reason_for_commitment_extension_or_removal: string | null
          scope: string | null
          status: string | null
          "sub-type": string | null
          target: string | null
          target_classification: string | null
          target_value: string | null
          target_wording: string | null
          target_year: string | null
          type: string | null
          year_type: string | null
        }
        Insert: {
          action?: string | null
          base_year?: string | null
          commitment_deadline?: string | null
          commitment_type?: string | null
          company_name: string
          company_temperature_alignment?: string | null
          date_published?: string | null
          full_target_language?: string | null
          lei?: string | null
          reason_for_commitment_extension_or_removal?: string | null
          scope?: string | null
          status?: string | null
          "sub-type"?: string | null
          target?: string | null
          target_classification?: string | null
          target_value?: string | null
          target_wording?: string | null
          target_year?: string | null
          type?: string | null
          year_type?: string | null
        }
        Update: {
          action?: string | null
          base_year?: string | null
          commitment_deadline?: string | null
          commitment_type?: string | null
          company_name?: string
          company_temperature_alignment?: string | null
          date_published?: string | null
          full_target_language?: string | null
          lei?: string | null
          reason_for_commitment_extension_or_removal?: string | null
          scope?: string | null
          status?: string | null
          "sub-type"?: string | null
          target?: string | null
          target_classification?: string | null
          target_value?: string | null
          target_wording?: string | null
          target_year?: string | null
          type?: string | null
          year_type?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "public_commitment_company_name_fkey"
            columns: ["company_name"]
            isOneToOne: true
            referencedRelation: "company"
            referencedColumns: ["company_name"]
          },
        ]
      }
      company: {
        Row: {
          autogenerated_contact: string | null
          company_name: string
          company_url: string | null
          industry: string | null
          isic: string | null
          lei: string | null
          net_zero_year: string | null
          sbt_near_term_target: string | null
          sbt_near_term_year: string | null
          sbt_status: string | null
          source_reports_page: string | null
          sustainability_contact_email: string | null
          sustainability_contact_linkedin: string | null
          sustainability_contact_name: string | null
        }
        Insert: {
          autogenerated_contact?: string | null
          company_name: string
          company_url?: string | null
          industry?: string | null
          isic?: string | null
          lei?: string | null
          net_zero_year?: string | null
          sbt_near_term_target?: string | null
          sbt_near_term_year?: string | null
          sbt_status?: string | null
          source_reports_page?: string | null
          sustainability_contact_email?: string | null
          sustainability_contact_linkedin?: string | null
          sustainability_contact_name?: string | null
        }
        Update: {
          autogenerated_contact?: string | null
          company_name?: string
          company_url?: string | null
          industry?: string | null
          isic?: string | null
          lei?: string | null
          net_zero_year?: string | null
          sbt_near_term_target?: string | null
          sbt_near_term_year?: string | null
          sbt_status?: string | null
          source_reports_page?: string | null
          sustainability_contact_email?: string | null
          sustainability_contact_linkedin?: string | null
          sustainability_contact_name?: string | null
        }
        Relationships: []
      }
      emission: {
        Row: {
          "all_cats?": string | null
          "cat._1": string | null
          "cat._10": string | null
          "cat._11": string | null
          "cat._12": string | null
          "cat._13": string | null
          "cat._14": string | null
          "cat._15": string | null
          "cat._2": string | null
          "cat._3": string | null
          "cat._4": string | null
          "cat._5": string | null
          "cat._6": string | null
          "cat._7": string | null
          "cat._8": string | null
          "cat._9": string | null
          comment: string | null
          company_name: string
          "cradle-to-gate_emissions_/_sek": string | null
          currency: string | null
          emission_intensity: string | null
          emission_page: string | null
          fiscal_year: string | null
          ghg_standard: string | null
          hq_country_move: string | null
          industry: string | null
          "isic_rev._4.": string | null
          page_revenue: string | null
          publication_date: string | null
          revenue: string | null
          revenue_sek: string | null
          scope_1: string | null
          scope_1_share_of_total_upstream_emissions: string | null
          scope_2: string | null
          "scope_2_location-based": string | null
          "scope_2_market-based": string | null
          scope_2_type: string | null
          scope_2_unknown: string | null
          share_upstream_of_scope_3: string | null
          source: string | null
          source_emisions_page_move: string | null
          "source_emission_/_report": string | null
          source_revenue: string | null
          status: string | null
          "total_emission_location-based": string | null
          "total_emission_market-based": string | null
          "total_reported_emission_scope_1+2": string | null
          "total_reported_emission_scope_1+2+3": string | null
          total_scope_3: string | null
          total_upstream_emissions: string | null
          upstream_scope_3: string | null
          year: number
        }
        Insert: {
          "all_cats?"?: string | null
          "cat._1"?: string | null
          "cat._10"?: string | null
          "cat._11"?: string | null
          "cat._12"?: string | null
          "cat._13"?: string | null
          "cat._14"?: string | null
          "cat._15"?: string | null
          "cat._2"?: string | null
          "cat._3"?: string | null
          "cat._4"?: string | null
          "cat._5"?: string | null
          "cat._6"?: string | null
          "cat._7"?: string | null
          "cat._8"?: string | null
          "cat._9"?: string | null
          comment?: string | null
          company_name: string
          "cradle-to-gate_emissions_/_sek"?: string | null
          currency?: string | null
          emission_intensity?: string | null
          emission_page?: string | null
          fiscal_year?: string | null
          ghg_standard?: string | null
          hq_country_move?: string | null
          industry?: string | null
          "isic_rev._4."?: string | null
          page_revenue?: string | null
          publication_date?: string | null
          revenue?: string | null
          revenue_sek?: string | null
          scope_1?: string | null
          scope_1_share_of_total_upstream_emissions?: string | null
          scope_2?: string | null
          "scope_2_location-based"?: string | null
          "scope_2_market-based"?: string | null
          scope_2_type?: string | null
          scope_2_unknown?: string | null
          share_upstream_of_scope_3?: string | null
          source?: string | null
          source_emisions_page_move?: string | null
          "source_emission_/_report"?: string | null
          source_revenue?: string | null
          status?: string | null
          "total_emission_location-based"?: string | null
          "total_emission_market-based"?: string | null
          "total_reported_emission_scope_1+2"?: string | null
          "total_reported_emission_scope_1+2+3"?: string | null
          total_scope_3?: string | null
          total_upstream_emissions?: string | null
          upstream_scope_3?: string | null
          year: number
        }
        Update: {
          "all_cats?"?: string | null
          "cat._1"?: string | null
          "cat._10"?: string | null
          "cat._11"?: string | null
          "cat._12"?: string | null
          "cat._13"?: string | null
          "cat._14"?: string | null
          "cat._15"?: string | null
          "cat._2"?: string | null
          "cat._3"?: string | null
          "cat._4"?: string | null
          "cat._5"?: string | null
          "cat._6"?: string | null
          "cat._7"?: string | null
          "cat._8"?: string | null
          "cat._9"?: string | null
          comment?: string | null
          company_name?: string
          "cradle-to-gate_emissions_/_sek"?: string | null
          currency?: string | null
          emission_intensity?: string | null
          emission_page?: string | null
          fiscal_year?: string | null
          ghg_standard?: string | null
          hq_country_move?: string | null
          industry?: string | null
          "isic_rev._4."?: string | null
          page_revenue?: string | null
          publication_date?: string | null
          revenue?: string | null
          revenue_sek?: string | null
          scope_1?: string | null
          scope_1_share_of_total_upstream_emissions?: string | null
          scope_2?: string | null
          "scope_2_location-based"?: string | null
          "scope_2_market-based"?: string | null
          scope_2_type?: string | null
          scope_2_unknown?: string | null
          share_upstream_of_scope_3?: string | null
          source?: string | null
          source_emisions_page_move?: string | null
          "source_emission_/_report"?: string | null
          source_revenue?: string | null
          status?: string | null
          "total_emission_location-based"?: string | null
          "total_emission_market-based"?: string | null
          "total_reported_emission_scope_1+2"?: string | null
          "total_reported_emission_scope_1+2+3"?: string | null
          total_scope_3?: string | null
          total_upstream_emissions?: string | null
          upstream_scope_3?: string | null
          year?: number
        }
        Relationships: [
          {
            foreignKeyName: "public_emission_company_name_fkey"
            columns: ["company_name"]
            isOneToOne: false
            referencedRelation: "company"
            referencedColumns: ["company_name"]
          },
        ]
      }
      target: {
        Row: {
          action: string | null
          base_year: number | null
          commitment_deadline: string | null
          commitment_type: string | null
          company_name: string
          company_temperature_alignment: string | null
          date_published: string | null
          full_target_language: string | null
          lei: string | null
          reason_for_commitment_extension_or_removal: string | null
          scope: string
          status: string | null
          "sub-type": string | null
          target: string | null
          target_classification: string | null
          target_value: string | null
          target_wording: string | null
          target_year: number
          type: string
          year_type: string | null
        }
        Insert: {
          action?: string | null
          base_year?: number | null
          commitment_deadline?: string | null
          commitment_type?: string | null
          company_name: string
          company_temperature_alignment?: string | null
          date_published?: string | null
          full_target_language?: string | null
          lei?: string | null
          reason_for_commitment_extension_or_removal?: string | null
          scope: string
          status?: string | null
          "sub-type"?: string | null
          target?: string | null
          target_classification?: string | null
          target_value?: string | null
          target_wording?: string | null
          target_year: number
          type: string
          year_type?: string | null
        }
        Update: {
          action?: string | null
          base_year?: number | null
          commitment_deadline?: string | null
          commitment_type?: string | null
          company_name?: string
          company_temperature_alignment?: string | null
          date_published?: string | null
          full_target_language?: string | null
          lei?: string | null
          reason_for_commitment_extension_or_removal?: string | null
          scope?: string
          status?: string | null
          "sub-type"?: string | null
          target?: string | null
          target_classification?: string | null
          target_value?: string | null
          target_wording?: string | null
          target_year?: number
          type?: string
          year_type?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "public_target_company_name_fkey"
            columns: ["company_name"]
            isOneToOne: false
            referencedRelation: "company"
            referencedColumns: ["company_name"]
          },
        ]
      }
      temp_company: {
        Row: {
          company_name: string | null
        }
        Insert: {
          company_name?: string | null
        }
        Update: {
          company_name?: string | null
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type PublicSchema = Database[Extract<keyof Database, "public">]

export type Tables<
  PublicTableNameOrOptions extends
  | keyof (PublicSchema["Tables"] & PublicSchema["Views"])
  | { schema: keyof Database },
  TableName extends PublicTableNameOrOptions extends { schema: keyof Database }
  ? keyof (Database[PublicTableNameOrOptions["schema"]]["Tables"] &
    Database[PublicTableNameOrOptions["schema"]]["Views"])
  : never = never,
> = PublicTableNameOrOptions extends { schema: keyof Database }
  ? (Database[PublicTableNameOrOptions["schema"]]["Tables"] &
    Database[PublicTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
  ? R
  : never
  : PublicTableNameOrOptions extends keyof (PublicSchema["Tables"] &
    PublicSchema["Views"])
  ? (PublicSchema["Tables"] &
    PublicSchema["Views"])[PublicTableNameOrOptions] extends {
      Row: infer R
    }
  ? R
  : never
  : never

export type TablesInsert<
  PublicTableNameOrOptions extends
  | keyof PublicSchema["Tables"]
  | { schema: keyof Database },
  TableName extends PublicTableNameOrOptions extends { schema: keyof Database }
  ? keyof Database[PublicTableNameOrOptions["schema"]]["Tables"]
  : never = never,
> = PublicTableNameOrOptions extends { schema: keyof Database }
  ? Database[PublicTableNameOrOptions["schema"]]["Tables"][TableName] extends {
    Insert: infer I
  }
  ? I
  : never
  : PublicTableNameOrOptions extends keyof PublicSchema["Tables"]
  ? PublicSchema["Tables"][PublicTableNameOrOptions] extends {
    Insert: infer I
  }
  ? I
  : never
  : never

export type TablesUpdate<
  PublicTableNameOrOptions extends
  | keyof PublicSchema["Tables"]
  | { schema: keyof Database },
  TableName extends PublicTableNameOrOptions extends { schema: keyof Database }
  ? keyof Database[PublicTableNameOrOptions["schema"]]["Tables"]
  : never = never,
> = PublicTableNameOrOptions extends { schema: keyof Database }
  ? Database[PublicTableNameOrOptions["schema"]]["Tables"][TableName] extends {
    Update: infer U
  }
  ? U
  : never
  : PublicTableNameOrOptions extends keyof PublicSchema["Tables"]
  ? PublicSchema["Tables"][PublicTableNameOrOptions] extends {
    Update: infer U
  }
  ? U
  : never
  : never

export type Enums<
  PublicEnumNameOrOptions extends
  | keyof PublicSchema["Enums"]
  | { schema: keyof Database },
  EnumName extends PublicEnumNameOrOptions extends { schema: keyof Database }
  ? keyof Database[PublicEnumNameOrOptions["schema"]]["Enums"]
  : never = never,
> = PublicEnumNameOrOptions extends { schema: keyof Database }
  ? Database[PublicEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : PublicEnumNameOrOptions extends keyof PublicSchema["Enums"]
  ? PublicSchema["Enums"][PublicEnumNameOrOptions]
  : never

