create type "public"."target_info" as ("target_type" text, "target_scope" character varying, "target_year" bigint, "target" text);

drop function if exists "public"."companies"(offset_value integer, limit_value integer, sort_by text, sort_order text);

create table "public"."temp_company" (
    "name" text,
    "industry" text,
    "isic" text,
    "hq_country" text,
    "company_url" text,
    "source_reports_page" text,
    "autogenerated_contact" text,
    "sustainability_contact_name" text,
    "sustainability_contact_email" text,
    "sustainability_contact_linkedin" text,
    "sbt_status" text,
    "sbt_near_term_year" text,
    "sbt_near_term_target" text,
    "net_zero_year" text
);


alter table "public"."temp_company" enable row level security;

alter table "public"."company" add column "hq_country" text;

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.companies(offset_value integer, limit_value integer, sort_by text, sort_order text, industry_filter text DEFAULT NULL::text)
 RETURNS TABLE(company_name character varying, industry text, commitment_type text, status text, commitment_deadline text, total_reported_emission_scope_1_2_3 double precision, revenue bigint, hq_country_move text, year bigint, currency text, emission_intensity double precision, targets target_info[])
 LANGUAGE plpgsql
AS $function$
DECLARE
    query TEXT;
BEGIN
    query := 'SELECT 
               c.name AS company_name, 
               c.industry,  -- Include industry from company
               cm.commitment_type, 
               cm.status, 
               cm.commitment_deadline,
               e.total_reported_emission_scope_1_2_3, 
               e.revenue, 
               e.hq_country_move, 
               e.year, 
               e.currency,
               e.emission_intensity,
               ARRAY_AGG(
                   ROW(t.type, t.scope, t.target_year, t.target)::target_info
               ) AS targets -- Aggregate composite type target_info
            FROM company c
            LEFT JOIN commitment cm ON c.name = cm.company_name
            LEFT JOIN (
                SELECT company_name, MAX(year) AS latest_year
                FROM emission
                GROUP BY company_name
            ) latest_emission ON c.name = latest_emission.company_name
            LEFT JOIN emission e ON c.name = e.company_name AND latest_emission.latest_year = e.year
            LEFT JOIN target t ON c.name = t.company_name
            WHERE e.total_reported_emission_scope_1_2_3 IS NOT NULL ';

    -- Apply filter based on industry if provided
    IF industry_filter IS NOT NULL THEN
        query := query || ' AND c.industry = ' || quote_literal(industry_filter);
    END IF;

    query := query || ' GROUP BY c.name, c.industry, cm.commitment_type, cm.status, cm.commitment_deadline, e.total_reported_emission_scope_1_2_3, e.revenue, e.hq_country_move, e.year, e.currency, e.emission_intensity'; -- Group by all non-aggregated columns

    IF sort_by = 'emission_intensity' THEN
        query := query || ' ORDER BY e.emission_intensity ';
    ELSE
        query := query || ' ORDER BY c.name ';
    END IF;

    IF sort_order = 'desc' THEN
        query := query || ' DESC ';
    END IF;

    query := query || ' OFFSET ' || offset_value || ' LIMIT ' || limit_value || ';';

    -- Execute the dynamically constructed query
    RETURN QUERY EXECUTE query;
END;
$function$
;

grant delete on table "public"."temp_company" to "anon";

grant insert on table "public"."temp_company" to "anon";

grant references on table "public"."temp_company" to "anon";

grant select on table "public"."temp_company" to "anon";

grant trigger on table "public"."temp_company" to "anon";

grant truncate on table "public"."temp_company" to "anon";

grant update on table "public"."temp_company" to "anon";

grant delete on table "public"."temp_company" to "authenticated";

grant insert on table "public"."temp_company" to "authenticated";

grant references on table "public"."temp_company" to "authenticated";

grant select on table "public"."temp_company" to "authenticated";

grant trigger on table "public"."temp_company" to "authenticated";

grant truncate on table "public"."temp_company" to "authenticated";

grant update on table "public"."temp_company" to "authenticated";

grant delete on table "public"."temp_company" to "service_role";

grant insert on table "public"."temp_company" to "service_role";

grant references on table "public"."temp_company" to "service_role";

grant select on table "public"."temp_company" to "service_role";

grant trigger on table "public"."temp_company" to "service_role";

grant truncate on table "public"."temp_company" to "service_role";

grant update on table "public"."temp_company" to "service_role";


