create or replace view "public"."company_slug" as  SELECT company.company_name,
    company.industry,
    company.isic,
    company.lei,
    company.company_url,
    company.source_reports_page,
    company.autogenerated_contact,
    company.sustainability_contact_name,
    company.sustainability_contact_email,
    company.sustainability_contact_linkedin,
    company.sbt_status,
    company.sbt_near_term_year,
    company.sbt_near_term_target,
    company.net_zero_year,
    regexp_replace(regexp_replace(lower(TRIM(BOTH FROM company.company_name)), ' |_|-'::text, '-'::text, 'g'::text), '[^a-zA-Z0-9-]'::text, ''::text, 'g'::text) AS slug
   FROM company;



