create table "public"."commitment" (
    "company_name" text not null,
    "lei" text,
    "action" text,
    "commitment_type" text,
    "commitment_deadline" text,
    "status" text,
    "reason_for_commitment_extension_or_removal" text,
    "full_target_language" text,
    "company_temperature_alignment" text,
    "target" text,
    "target_wording" text,
    "scope" text,
    "target_value" text,
    "type" text,
    "sub-type" text,
    "target_classification" text,
    "base_year" text,
    "target_year" text,
    "year_type" text,
    "date_published" text
);


alter table "public"."commitment" enable row level security;

create table "public"."company" (
    "company_name" character varying not null,
    "industry" text,
    "isic" text,
    "lei" text,
    "company_url" text,
    "source_reports_page" text,
    "autogenerated_contact" text,
    "sustainability_contact_name" text,
    "sustainability_contact_email" text,
    "sustainability_contact_linkedin" text,
    "sbt_status" text,
    "sbt_near_term_year" text,
    "sbt_near_term_target" text,
    "net_zero_year" text
);


alter table "public"."company" enable row level security;

create table "public"."emission" (
    "source" text,
    "year" bigint not null,
    "fiscal_year" text,
    "company_name" text not null,
    "industry" text,
    "isic_rev._4." text,
    "hq_country_move" text,
    "scope_1" text,
    "scope_2" text,
    "scope_2_type" text,
    "scope_2_market-based" text,
    "scope_2_location-based" text,
    "scope_2_unknown" text,
    "total_scope_3" text,
    "total_emission_market-based" text,
    "total_emission_location-based" text,
    "total_reported_emission_scope_1+2" text,
    "total_reported_emission_scope_1+2+3" text,
    "cat._1" text,
    "cat._2" text,
    "cat._3" text,
    "cat._4" text,
    "cat._5" text,
    "cat._6" text,
    "cat._7" text,
    "cat._8" text,
    "cat._9" text,
    "cat._10" text,
    "cat._11" text,
    "cat._12" text,
    "cat._13" text,
    "cat._14" text,
    "cat._15" text,
    "all_cats?" text,
    "upstream_scope_3" text,
    "share_upstream_of_scope_3" text,
    "scope_1_share_of_total_upstream_emissions" text,
    "total_upstream_emissions" text,
    "revenue" text,
    "currency" text,
    "revenue_sek" text,
    "cradle-to-gate_emissions_/_sek" text,
    "ghg_standard" text,
    "source_emisions_page_move" text,
    "emission_intensity" text,
    "source_emission_/_report" text,
    "emission_page" text,
    "source_revenue" text,
    "page_revenue" text,
    "publication_date" text,
    "comment" text,
    "status" text
);


alter table "public"."emission" enable row level security;

create table "public"."target" (
    "company_name" character varying not null,
    "lei" text,
    "action" text,
    "commitment_type" text,
    "commitment_deadline" text,
    "status" text,
    "reason_for_commitment_extension_or_removal" text,
    "full_target_language" text,
    "company_temperature_alignment" text,
    "target" text,
    "target_wording" text,
    "scope" character varying not null,
    "target_value" text,
    "type" text not null,
    "sub-type" text,
    "target_classification" text,
    "base_year" bigint,
    "target_year" bigint not null,
    "year_type" text,
    "date_published" text
);


alter table "public"."target" enable row level security;

CREATE UNIQUE INDEX commitment_pkey ON public.commitment USING btree (company_name);

CREATE UNIQUE INDEX company_company_name_key ON public.company USING btree (company_name);

CREATE UNIQUE INDEX company_pkey ON public.company USING btree (company_name);

CREATE UNIQUE INDEX emission_pkey ON public.emission USING btree (year, company_name);

CREATE UNIQUE INDEX target_pkey ON public.target USING btree (company_name, scope, type, target_year);

alter table "public"."commitment" add constraint "commitment_pkey" PRIMARY KEY using index "commitment_pkey";

alter table "public"."company" add constraint "company_pkey" PRIMARY KEY using index "company_pkey";

alter table "public"."emission" add constraint "emission_pkey" PRIMARY KEY using index "emission_pkey";

alter table "public"."target" add constraint "target_pkey" PRIMARY KEY using index "target_pkey";

alter table "public"."commitment" add constraint "public_commitment_company_name_fkey" FOREIGN KEY (company_name) REFERENCES company(company_name) not valid;

alter table "public"."commitment" validate constraint "public_commitment_company_name_fkey";

alter table "public"."company" add constraint "company_company_name_key" UNIQUE using index "company_company_name_key";

alter table "public"."emission" add constraint "public_emission_company_name_fkey" FOREIGN KEY (company_name) REFERENCES company(company_name) not valid;

alter table "public"."emission" validate constraint "public_emission_company_name_fkey";

alter table "public"."target" add constraint "public_target_company_name_fkey" FOREIGN KEY (company_name) REFERENCES company(company_name) not valid;

alter table "public"."target" validate constraint "public_target_company_name_fkey";

grant delete on table "public"."commitment" to "anon";

grant insert on table "public"."commitment" to "anon";

grant references on table "public"."commitment" to "anon";

grant select on table "public"."commitment" to "anon";

grant trigger on table "public"."commitment" to "anon";

grant truncate on table "public"."commitment" to "anon";

grant update on table "public"."commitment" to "anon";

grant delete on table "public"."commitment" to "authenticated";

grant insert on table "public"."commitment" to "authenticated";

grant references on table "public"."commitment" to "authenticated";

grant select on table "public"."commitment" to "authenticated";

grant trigger on table "public"."commitment" to "authenticated";

grant truncate on table "public"."commitment" to "authenticated";

grant update on table "public"."commitment" to "authenticated";

grant delete on table "public"."commitment" to "service_role";

grant insert on table "public"."commitment" to "service_role";

grant references on table "public"."commitment" to "service_role";

grant select on table "public"."commitment" to "service_role";

grant trigger on table "public"."commitment" to "service_role";

grant truncate on table "public"."commitment" to "service_role";

grant update on table "public"."commitment" to "service_role";

grant delete on table "public"."company" to "anon";

grant insert on table "public"."company" to "anon";

grant references on table "public"."company" to "anon";

grant select on table "public"."company" to "anon";

grant trigger on table "public"."company" to "anon";

grant truncate on table "public"."company" to "anon";

grant update on table "public"."company" to "anon";

grant delete on table "public"."company" to "authenticated";

grant insert on table "public"."company" to "authenticated";

grant references on table "public"."company" to "authenticated";

grant select on table "public"."company" to "authenticated";

grant trigger on table "public"."company" to "authenticated";

grant truncate on table "public"."company" to "authenticated";

grant update on table "public"."company" to "authenticated";

grant delete on table "public"."company" to "service_role";

grant insert on table "public"."company" to "service_role";

grant references on table "public"."company" to "service_role";

grant select on table "public"."company" to "service_role";

grant trigger on table "public"."company" to "service_role";

grant truncate on table "public"."company" to "service_role";

grant update on table "public"."company" to "service_role";

grant delete on table "public"."emission" to "anon";

grant insert on table "public"."emission" to "anon";

grant references on table "public"."emission" to "anon";

grant select on table "public"."emission" to "anon";

grant trigger on table "public"."emission" to "anon";

grant truncate on table "public"."emission" to "anon";

grant update on table "public"."emission" to "anon";

grant delete on table "public"."emission" to "authenticated";

grant insert on table "public"."emission" to "authenticated";

grant references on table "public"."emission" to "authenticated";

grant select on table "public"."emission" to "authenticated";

grant trigger on table "public"."emission" to "authenticated";

grant truncate on table "public"."emission" to "authenticated";

grant update on table "public"."emission" to "authenticated";

grant delete on table "public"."emission" to "service_role";

grant insert on table "public"."emission" to "service_role";

grant references on table "public"."emission" to "service_role";

grant select on table "public"."emission" to "service_role";

grant trigger on table "public"."emission" to "service_role";

grant truncate on table "public"."emission" to "service_role";

grant update on table "public"."emission" to "service_role";

grant delete on table "public"."target" to "anon";

grant insert on table "public"."target" to "anon";

grant references on table "public"."target" to "anon";

grant select on table "public"."target" to "anon";

grant trigger on table "public"."target" to "anon";

grant truncate on table "public"."target" to "anon";

grant update on table "public"."target" to "anon";

grant delete on table "public"."target" to "authenticated";

grant insert on table "public"."target" to "authenticated";

grant references on table "public"."target" to "authenticated";

grant select on table "public"."target" to "authenticated";

grant trigger on table "public"."target" to "authenticated";

grant truncate on table "public"."target" to "authenticated";

grant update on table "public"."target" to "authenticated";

grant delete on table "public"."target" to "service_role";

grant insert on table "public"."target" to "service_role";

grant references on table "public"."target" to "service_role";

grant select on table "public"."target" to "service_role";

grant trigger on table "public"."target" to "service_role";

grant truncate on table "public"."target" to "service_role";

grant update on table "public"."target" to "service_role";

create policy "All authenticated and anonymous users can select"
on "public"."commitment"
as permissive
for select
to authenticated, anon
using (true);


create policy "All authenticated and anonymous users can select"
on "public"."company"
as permissive
for select
to authenticated, anon
using (true);


create policy "All authenticated and anonymous users can select"
on "public"."emission"
as permissive
for select
to authenticated, anon
using (true);


create policy "All authenticated and anonymous users can select"
on "public"."target"
as permissive
for select
to authenticated, anon
using (true);



